#
# Makefile for the Sensor driver
#

# Each configuration option enables a list of files.

obj-$(CONFIG_INPUT_SENSOR) += gsensor.o

obj-$(CONFIG_WMT_SENSOR_KXTI9) += kxti9_gsensor/

obj-$(CONFIG_WMT_SENSOR_DMT08) += dmt08_gsensor/
